# Site settings
title: Fountain of Life Covenant Church
email: matt@lookitscook.com
description:
baseurl: "/folmadison.org" # the subpath of your site, e.g. /blog/
url: "http://www.folmadison.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
